# start with the production blender image
FROM blender_0

RUN apt-get update
RUN apt-get install -y python3-pip
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY main.py .
COPY tasks.py .

# start the rq worker process
CMD ["rq", "worker", "--url", "redis://redis:6379", "render_queue"]

