apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: render-data-pvc
spec: 
  accessModes:
    - ReadWriteMany # multiple workers can mount and write
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
spec:
  accessModes:
    - ReadWriteOnce # only one pod (redis) is allowed to write
  resources:
    requests:
      storage: 2Gi

