# api.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: render-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: render-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
        volumeMounts:
        - mountPath: /render_data 
          name: shared-storage
      # --- FIX: volumes moved out of the container list and under spec ---
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: render-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer # Exposes port 8000 to your local Mac browser
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
